image: 3.8.3-jdk-11
stages:
  - compile
  - verify

compile:
  stage: compile
  script:
    - cd pmdb
    - mvn compile

verify:
  stage: verify
  script:
    - cd pmdb
    - mvn verify -f core/pom.xml
